/**
 * One version, four places that print it.
 *
 * The version had drifted: package.json said 0.3.6, the committed docs site
 * said 0.3.5, README.md and Prompt.md still said 0.3.4, and the published site
 * said something else again. Every one of those was hand-copied, and nothing
 * ever compared them.
 *
 * package.json is the source of truth. `stampVersions()` rewrites the others
 * from it, `checkVersions()` proves they agree. The release runs both, and
 * preflight runs the check so drift is visible at the start of a session
 * instead of at the end of one.
 */
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './paths.js';

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const write = (rel, text) => fs.writeFileSync(path.join(ROOT, rel), text, 'utf8');
const exists = (rel) => fs.existsSync(path.join(ROOT, rel));

export const currentVersion = () => JSON.parse(read('package.json')).version;

/**
 * Each surface: where it lives, the pattern that finds the version in it, and
 * how to write a new one. Adding a surface here is what makes it checked.
 */
const SURFACES = [
  {
    file: 'memory.json',
    find: (s) => JSON.parse(s).version,
    set: (s, v) => {
      const m = JSON.parse(s);
      m.version = v;
      m.lastUpdated = new Date().toISOString().slice(0, 10);
      return `${JSON.stringify(m, null, 2)}\n`;
    },
  },
  {
    file: 'README.md',
    find: (s) => s.match(/\*\*Version v(\d+\.\d+\.\d+)\*\*/)?.[1],
    set: (s, v) => s.replace(/\*\*Version v\d+\.\d+\.\d+\*\*/, `**Version v${v}**`),
  },
  {
    file: 'Prompt.md',
    find: (s) => s.match(/## Current implementation state \(v(\d+\.\d+\.\d+)\)/)?.[1],
    set: (s, v) => s.replace(/## Current implementation state \(v\d+\.\d+\.\d+\)/,
      `## Current implementation state (v${v})`),
  },
  {
    file: 'site/index.html',
    find: (s) => s.match(/Nebula v(\d+\.\d+\.\d+)/)?.[1],
    // Generated by build-site.js from package.json; never patched in place.
    set: null,
  },
];

/** Rewrite every writable surface from package.json. @returns {string[]} changed files */
export function stampVersions(version = currentVersion()) {
  const changed = [];
  for (const s of SURFACES) {
    if (!s.set || !exists(s.file)) continue;
    const before = read(s.file);
    const after = s.set(before, version);
    if (after !== before) {
      write(s.file, after);
      changed.push(s.file);
    }
  }
  return changed;
}

/** @returns {{ok: boolean, version: string, rows: {file: string, found: string|undefined, ok: boolean}[]}} */
export function checkVersions(version = currentVersion()) {
  const rows = SURFACES
    .filter((s) => exists(s.file))
    .map((s) => {
      const found = s.find(read(s.file));
      return { file: s.file, found, ok: found === version };
    });
  return { ok: rows.every((r) => r.ok), version, rows };
}

/** Run directly: `node scripts/versions.js` prints the table and exits non-zero on drift. */
if (process.argv[1] && process.argv[1].endsWith('versions.js')) {
  const { ok, version, rows } = checkVersions();
  console.log(`package.json  ${version}`);
  for (const r of rows) {
    console.log(`  ${r.ok ? 'ok  ' : 'DRIFT'} ${r.file.padEnd(18)} ${r.found ?? '(not found)'}`);
  }
  if (!ok) {
    console.error('\nVersions disagree. `npm run push` restamps them; to fix by hand, edit the files above.');
    process.exit(1);
  }
  console.log('\nall surfaces agree');
}
